### ISSUE TITLE
How to add custom login screen?

### ISSUE THREAD

**Issue by rubiktubik** [joinfaces/joinfaces-example#58]
How can i add my custom login screen?

I tried the tutorial at [here](http://docs.spring.io/spring-security/site/docs/3.2.x/guides/form.html) 
but i doesnt seems to work

**Comment by persapiens** [comment]
Hi @rubiktubik ,

First of all, you should see [this tutorial](http://docs.spring.io/spring-security/site/docs/4.1.1.RELEASE/guides/html5/form-javaconfig.html), because joinfaces 2.2.0 uses spring boot 1.4.0 and spring security 4.1.1.

Could you provide an example project? It would improve our discussion.

I look forward your answer.
Marcelo

**Comment by luxuryfellow** [comment]
I also need custom login page.
can you show me a example? 
please...

**Comment by persapiens** [comment]
Hello @rubiktubik and @luxuryfellow ,

I've just pushed one possible implementation in #65 

Could you verify if it helps you?
